[package]
name = "macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10.0"
smol = "1.2.5"
surf = "2.3.1"
futures = "0.3"

